export const GET_ADMIN_DATA = "app/Admin/GET_ADMIN_DATA";
export const GET_ADMIN_DATA_SUCCEEDED = "app/Admin/GET_ADMIN_DATA_SUCCEEDED";
export const SET_ADMIN_LAYOUT = "app/Admin/SET_ADMIN_LAYOUT";
export const SET_CTM_ADMIN_LAYOUT = "app/Admin/SET_CTM_ADMIN_LAYOUT";
export const SET_HIDE_PLUGIN_USERS_PERMISSSIONS = "app/Admin/SET_HIDE_PLUGIN_USERS_PERMISSSIONS";
